language: java
jdk: oracalejdk11

script: mvn -e verify

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - ilya.tfb@yandex.ru
    on_failure: always
    on_success: change
